### ISSUE TITLE
Desativar automaticamente quando estiver afk na cidade

### ISSUE THREAD

**Issue by biancaazuma** [biancaazuma/4RTools-RagTools#23]
foi sugerido pelo player de validar o hp e sp algumas vezes, se não mudarem desativa o 4rtools

**Comment by gcrestani** [comment]
Sugestão:
Validar se está na cidade e não usar nenhuma pot/buff (ou desativar o 4RTools). Dessa forma evita gastar consumíveis curando hp e sp ao morrer (invés de usar o NPC Curandeira).
O projeto original tamém tem um Issue parecido com um rascunho não terminado:
https://github.com/4RTools/4RTools/issues/27
